### PR TITLE
Marching optimization

### PR DESCRIPTION
**Pull request by kecnry**
related to #124 (already closed)

### CODE REVIEW

**Comment by kecnry** [comment]
@horvatm - can you look into why this is failing to build.  It seems to build locally for me, but travis is failing to build it with any compiler (click the red x next to the commits above to see the logs).  Once all tests pass, I'll merge into development.

**Comment by kecnry** [comment]
Does this change our compiler requirements?  Before we were building correctly with lower versions of g++, right?

**Comment by horvatm** [comment]
No. I just correctly set the compiler to g++-5.

**Comment by kecnry** [comment]
merging and adding compiler requirements into the development branch of the documentation.

**Pull request merged**
